'use client'
import { useState, useEffect } from 'react'
import { useRouter } from 'next/navigation'
import { Link as LinkIcon } from 'lucide-react'
import axios from 'axios'
import jsPDF from 'jspdf';
import autoTable from 'jspdf-autotable';

import '@fortawesome/fontawesome-free/css/all.min.css';
import { PieChart, Pie, Cell, Tooltip, ResponsiveContainer, Legend } from 'recharts';


const Page = () => {
  const router = useRouter()
  const [website, setWebsite] = useState("")
  const [result, setResult] = useState(null)
  const [loading, setLoading] = useState(false)

useEffect(() => {
    const token = localStorage.getItem("token")
    if (!token) {
      if (!window.hasShownAlert) {
        window.hasShownAlert = true;
      alert("Please login first to use this tool!")
      router.push('/signin')
      setTimeout(() => { window.hasShownAlert = false; }, 3000);
      } 
    }
  }, [])

const handleSubmit = async (e) => {
  e.preventDefault();
  setResult(null); // 🟢 Sabse pehle purana data saaf karein
  setLoading(true);

  try {
    const token = localStorage.getItem("token");
    const res = await axios.post(
      "http://localhost:5000/api/orphan",
      { website },
      { headers: { Authorization: `Bearer ${token}` } }
    );

    // 🔍 Check karein terminal data match ho raha hai
    console.log("Naya Data Aaya:", res.data); 
    setResult(res.data); // 🟢 Naya 138 wala data yahan set hoga

  } catch (error) {
    console.error(error);
  } finally {
    setLoading(false);
  }
};

const downloadOrphanPDF = async () => {
  const doc = new jsPDF('p', 'mm', 'a4');
  const today = new Date().toLocaleDateString('en-GB');

  // 1. CALCULATIONS (Variables ko define kiya taaki error na aaye)
  const healthy = (result.totalInSitemap || 0) - (result.count || 0);
  const orphan = result.count || 0;
  const total = healthy + orphan;
  const healthScore = total > 0 ? ((healthy / total) * 100).toFixed(1) : 0;

  // --- 2. HEADER ---
  // --- 2. HEADER (Logo with Background Box) ---
  // ✅ NAYA UPDATED HEADER CODE (Orange Box Removed + Wide Logo):
try {
    const logoX = 15;
    const logoY = 10;
    
    // 🟢 Width ko 25 kar diya hai taaki logo bada dikhe
    const logoWidth = 25; 
    const logoHeight = 14;

    // Logo Image (Direct add kiya bina box ke)
    doc.addImage("/logo/pdf logo.png", "PNG", logoX, logoY, logoWidth, logoHeight); 

    // Branding Text (Position 50 rakhi hai taaki bade logo se door rahe)
    doc.setFont("helvetica", "bold");
    doc.setFontSize(22);
    doc.setTextColor(237, 109, 7);
    doc.text("LINKSENTINEL", 50, 23); 

} catch (e) {
    console.log("Logo not found");
}// 🟢 22 se 23 kiya taaki logo ke center mein dikhe

  doc.setFontSize(9);
  doc.setTextColor(150);
  doc.text("REPORT GENERATED BY LINKSENTINEL.COM", 195, 21, { align: "right" });

  doc.setDrawColor(220);
  doc.line(15, 33, 195, 33); // 🟢 Line ko 1mm niche shift kiya taaki logo box se na takraye
  // --- 3. TITLE & WEBSITE INFO ---
 doc.setFont("helvetica", "bold");
doc.setFontSize(18);
doc.setTextColor(30, 41, 59);
doc.text("Orphan Page Analysis", 15, 42); // 🟢 Position fix ki

// 2. Target Website Box (URL Button Look)
const targetBoxY = 48; // 🟢 Height adjust ki spacing ke liye
doc.setFillColor(248, 250, 252);
doc.setDrawColor(220);
doc.roundedRect(15, targetBoxY, 130, 12, 2, 2, "FD");

// Orange Badge
doc.setFillColor(237, 109, 7);
doc.roundedRect(17, targetBoxY + 2, 32, 8, 1, 1, "F");
doc.setFontSize(7.5);
doc.setTextColor(255);
doc.text("TARGET WEBSITE", 33, targetBoxY + 7.5, { align: "center" });

// Website URL
doc.setFontSize(9);
doc.setTextColor(30, 41, 59);
doc.setFont("helvetica", "normal");
doc.text(website, 52, targetBoxY + 7.5);

// Date (Aligned with URL)
doc.setTextColor(120);
doc.text(`Date: ${today}`, 195, targetBoxY + 7.5, { align: "right" });

// 3. Summary Bar (Ab ye text ke niche aayega proper gap ke saath)
const summaryY = 65; // 🟢 Nayi position set ki
doc.setFillColor(245, 245, 245);
doc.roundedRect(15, summaryY, 180, 12, 2, 2, "F");

doc.setFontSize(10);
doc.setTextColor(60);
// 🟢 Text ko box ke andar align kiya (Y: 73)
doc.text(`Healthy: ${healthy}`, 25, summaryY + 8); 
doc.setTextColor(239, 68, 68);
doc.text(`Orphan: ${orphan}`, 85, summaryY + 8);
doc.setTextColor(60);
doc.text(`Health Score: ${healthScore}%`, 145, summaryY + 8);

  // --- 4. VISUAL ANALYSIS BOX (Coordinates fix kiye hain) ---
  // pdf pie chart section
 const boxX = 120;
const boxY = 85;
const boxWidth = 75;
const boxHeight = 62;

// Draw box
doc.setFillColor(252, 252, 252);
doc.setDrawColor(240);
doc.roundedRect(boxX, boxY, boxWidth, boxHeight, 3, 3, "FD");

// Title
doc.setFontSize(11);
doc.setTextColor(30, 41, 59);

doc.setFont("helvetica", "bold");
doc.text("Visual Analysis", boxX + boxWidth / 2, boxY + 10, { align: "center" });

// ✅ Now calculate center AFTER defining box
const centerX = boxX + boxWidth / 2;
const centerY = boxY + boxHeight / 2 - 1;
const radius = 18;
// 🔥 Important (Add here)
doc.setLineWidth(0);
doc.setLineJoin("round");
doc.setLineCap("round");

if (total > 0) {

  const orphanFraction = orphan / total;
  const orphanAngle = orphanFraction * 2 * Math.PI;

  const healthyPercent = total > 0 ? ((healthy / total) * 100).toFixed(1) : 0;
const orphanPercent = total > 0 ? ((orphan / total) * 100).toFixed(1) : 0;

  // 1️⃣ Draw full green circle first (Healthy background)
  doc.setFillColor(16, 185, 129);
  doc.circle(centerX, centerY, radius, "F");



  // 2️⃣ Draw red slice on top
  if (orphan > 0) {

  doc.setFillColor(239, 68, 68);
  doc.setLineWidth(0);

  const startAngle = -Math.PI / 2;
  const endAngle = startAngle + orphanAngle;

  // Create slice using arc + lines
  doc.moveTo(centerX, centerY);

  const steps = 100; // higher = smoother
  for (let i = 0; i <= steps; i++) {
    const angle = startAngle + (i / steps) * (endAngle - startAngle);
    const x = centerX + radius * Math.cos(angle);
    const y = centerY + radius * Math.sin(angle);
    doc.lineTo(x, y);
  }

  doc.lineTo(centerX, centerY);
  doc.fill("F");
}

  // 3️⃣ White center hole (Doughnut effect)
  doc.setFillColor(255, 255, 255);
  doc.circle(centerX, centerY, 10, "F");

  const legendY = boxY + boxHeight - 12; // bottom area

doc.setFontSize(8);
doc.setFont("helvetica", "normal");
doc.setTextColor(60);

// 🟢 Healthy
doc.setFillColor(16, 185, 129);
doc.rect(boxX + 10, legendY, 4, 4, "F");

doc.text(
  `Healthy: ${healthyPercent}%`,
  boxX + 18,
  legendY + 3
);

// 🔴 Orphan
doc.setFillColor(239, 68, 68);
doc.rect(boxX + boxWidth / 2, legendY, 4, 4, "F");

doc.text(
  `Orphan: ${orphanPercent}%`,
  boxX + boxWidth / 2 + 8,
  legendY + 3
);
}
  // end pdf pie chart section

  // --- 5. DATA TABLE ---
  const pageWidth = doc.internal.pageSize.getWidth();

// Left table area: 15mm to 110mm
const tableStartX = 15;
const tableEndX = 110;
const tableWidth = tableEndX - tableStartX;

autoTable(doc, {
  startY: 85,
  margin: {
    left: tableStartX,
    right: pageWidth - tableEndX
  },

  head: [['Sr.', 'Orphan URL Path']],

  body: (result.data || []).map((url, i) => [
    i + 1,
    url
  ]),

  columnStyles: {
    0: { cellWidth: 15 },
    1: { cellWidth: tableWidth - 15 }
  },

  styles: {
    fontSize: 8,
    cellPadding: 3,
    overflow: 'linebreak',
    font: 'helvetica'
  },

  headStyles: {
    fillColor: [237, 109, 7],
    textColor: 255
  },

  theme: 'grid'
});

  // --- 6. FOOTER (Page Numbers) ---
  const pageCount = doc.internal.getNumberOfPages();
  for (let i = 1; i <= pageCount; i++) {
    doc.setPage(i);
    doc.setFontSize(8);
    doc.setTextColor(150);
    doc.text(`Page ${i} of ${pageCount} - By Linksentinel SEO Report`, 105, 285, { align: "center" });
  }

  doc.save(`LinkSentinel_Report_${today.replace(/\//g, '-')}.pdf`);
};
  return (
    <main className="m-8">
      <section className="mt-4 p-4 bg-gray-100 rounded-2xl">
      <h1 className="text-3xl md:text-4xl font-bold font-['Libre_Baskerville']">Orphan Page Checker</h1>
    <h2 className="text-xl font-semibold md:text-2xl font-['Libre_Baskerville']">Find Hidden Pages That Search Engines Can’t Discover</h2>
    <p className="text-xl md:text-2xl font-['Rosario']">Orphan pages are web pages that exist on your website but are not linked from any internal pages. Because search engines rely on internal links to crawl and discover content, orphan pages often remain unindexed or perform poorly in search results.</p>
    <p className="text-xl mt-2.5 md:text-2xl font-['Rosario']">This <span className="font-bold">Orphan Page Checker</span> analyzes your website structure using your sitemap and internal links to accurately identify orphan pages.</p>
    <p className="text-xl mt-2.5 md:text-2xl font-semibold  font-['Rosario']">Note: <span className='font-normal text-xl md:text-2xl'>*A valid XML sitemap is required for this analysis.*</span></p>
      </section>

      
    
<form onSubmit={handleSubmit} className="mt-2 p-4 ">
  <label
    htmlFor="website-url"
    className="text-2xl font-['Libre_Baskerville'] text-black"
  >
    Enter your website URL
  </label>

  <div className="flex items-center gap-3 mt-2">
    {/* Input */}
    <div className="flex items-center border-2 gap-2.5 p-2.5 border-gray-500 rounded-md w-[340px]">
      <LinkIcon size={20} absoluteStrokeWidth />
      <input
        className="text-black outline-none flex-1"
        type="url"
        id="website-url"
        placeholder="https://example.com"
        value={website}                     
        onChange={(e) => setWebsite(e.target.value)}
        required
      />
    </div>
    {/* Button */}
    <button
      type="submit"
      className="finline-flex items-center justify-center px-3 py-2 mr-3 text-xl font-['Lora'] font-medium text-center text-white rounded-lg bg-red-600 ring-2 ring-red-600 ring-offset-2 cursor-pointer transition-transform transform hover:scale-95"
    >
      <i className="fa-brands fa-searchengin fa-lg"></i>
      <span>Analysis</span>
    </button>
  </div>
  {/* note text  */}
  <p className="mt-2 text-red-600 text-sm">
    *Make sure your Website Url is valid.
  </p>
</form>

{loading && (
  <div className="mt-4 p-4 bg-blue-50 border-l-4 border-blue-500 text-blue-700 animate-pulse">
    <p className="font-bold font-['Rosario'] text-xl">Processing Analysis...</p>
    <p className="text-sm italic text-gray-600">The tool is scanning your sitemap and crawling internal links. Please wait.</p>
  </div>
)}

{/*New Result */}
{/* 🟢 FINAL RESULT SECTION: Side-by-Side Layout with Scrolling & Bottom Button */}
{result && (
  <section className="mt-6 p-6 bg-white border-2 border-red-500 rounded-2xl shadow-lg">
    <h2 className="text-2xl font-bold text-red-600 mb-6 border-b pb-2 font-['Libre_Baskerville']">
      Orphan Page Report
    </h2>
    
    <div className="flex flex-col md:flex-row gap-8 items-start">
      {/* LEFT SIDE: Statistics & Scrolling URL List */}
      <div className="w-full md:w-3/5">
        {/* Statistics Row */}
        <div className="grid grid-cols-2 gap-4 mb-6">
          <div className="p-4 bg-gray-100 rounded-lg border border-gray-200 shadow-sm">
            <p className="text-gray-500 font-bold text-[10px] uppercase tracking-wider">Total Sitemap URLs</p>
            <p className="text-4xl font-bold text-gray-800">{result.totalInSitemap || 0}</p> 
          </div>
          <div className="p-4 bg-red-50 rounded-lg border border-red-100 shadow-sm">
            <p className="text-red-700 font-bold text-[10px] uppercase tracking-wider">Orphan Pages Found</p>
            <p className="text-4xl font-bold text-red-600">{result.count || 0}</p>
          </div>
        </div>

        {/* Scrollable URL List */}
        <h3 className="font-bold text-lg mb-2 font-['Libre_Baskerville'] text-black">Detected URLs:</h3>
        <div className="max-h-64 overflow-y-auto border-2 border-gray-100 p-3 rounded-xl bg-gray-50 shadow-inner scrollbar-thin scrollbar-thumb-gray-300">
          <ul className="list-disc pl-5 space-y-2">
            {(result.data || []).map((url, index) => (
              <li key={index} className="text-blue-600 text-sm break-all font-['Rosario'] hover:text-red-600 transition-colors">
                {url}
              </li>
            ))}
            {(!result.data || result.data.length === 0) && (
              <p className="text-green-600 font-bold italic text-center p-4">Zero Orphan Pages Found!</p>
            )}
          </ul>
        </div>
       
      </div>

      {/* RIGHT SIDE: Visual Analysis & PDF Button Below */}
      <div className="w-full md:w-2/5 flex flex-col items-center">
        {/* Pie Chart Box */}
        <div id="orphanChart" className="w-full bg-white p-4 rounded-xl border border-gray-100 flex flex-col items-center mb-4">
          <h3 className="text-center font-bold text-gray-700 mb-2 font-['Libre_Baskerville'] text-sm">Visual Analysis</h3>
          <div id="chartArea" className="h-64 w-full">
            <ResponsiveContainer width="100%" height="100%">
              <PieChart>
                <Pie
                  data={[
                    { name: 'Healthy Pages', value: (result.totalInSitemap || 0) - (result.count || 0) },
                    { name: 'Orphan Pages', value: result.count || 0 },
                  ]}
                  cx="50%" cy="50%" innerRadius={60} outerRadius={85} paddingAngle={5} dataKey="value"
                >
                  <Cell fill="#10B981" /> {/* Green for Healthy */}
                  <Cell fill="#EF4444" /> {/* Red for Orphan */}
                </Pie>
                <Tooltip />
                <Legend verticalAlign="bottom" height={36} />
              </PieChart>
            </ResponsiveContainer>
          </div>
        </div>

        {/* Download Button: Chart ke theek niche */}
        <button 
          onClick={downloadOrphanPDF}
          className="w-full bg-[#ED6D07] hover:bg-orange-600 text-white px-5 py-3 rounded-lg font-bold flex items-center justify-center gap-2 cursor-pointer shadow-lg transition-all active:scale-95"
        >
          <i className="fa-solid fa-file-pdf"></i> Download PDF Report
        </button>
      </div>
    </div>
  </section>
)}

<section className="mt-4 p-4 bg-gray-100 rounded-2xl">
        <h2 className="text-2xl md:text-3xl font-bold font-['Libre_Baskerville']">How the Orphan Page Checker Works.</h2>
        <p className="text-xl md:text-2xl font-['Rosario']">This tool follows a structured analysis process to ensure accurate results.</p>
        <p className="text-xl font-semibold md:text-2xl font-['Rosario']">Step-by-Step Process:</p>
        <ol className="list-decimal pl-6 mt-2">
          <li className="text-xl md:text-2xl font-['Rosario']">The tool searches for an XML sitemap on your website.</li> 
          <li className="text-xl md:text-2xl font-['Rosario']">All URLs listed in the sitemap are collected.</li>
          <li className="text-xl md:text-2xl font-['Rosario']">The tool crawls your website to identify internally linked pages.</li>
          <li className="text-xl md:text-2xl font-['Rosario']">Sitemap URLs are compared with internally linked URLs.</li>
          <li className="text-xl md:text-2xl font-['Rosario']">Pages present in the sitemap but missing internal links are identified as <span className='font-bold'>Orphan Pages</span>.</li>
        </ol>
        <p className="text-lg font-semibold  font-['Rosario']">Note: <span className='font-normal text-lg'>*If no sitemap is found, the analysis will not run.*</span></p>
      </section>

      <section className="mt-4 p-4 bg-gray-100 rounded-2xl">
        <h2 className="text-2xl md:text-3xl font-bold font-['Libre_Baskerville']">Why a Sitemap Is Required</h2>
        <p className="text-xl md:text-2xl font-['Rosario']">A sitemap provides a complete list of pages that exist on your website.</p>
        <p className="text-xl md:text-2xl font-['Rosario']">Without it, the tool cannot determine whether a page exists but lacks internal links.</p>
        <p className="text-xl font-bold md:text-2xl font-['Rosario']">Sitemap Benefits:</p>
        <ul className="list-disc pl-6 mt-2">
          <li className="text-xl md:text-2xl font-['Rosario']">Helps search engines discover all pages</li> 
          <li className="text-xl md:text-2xl font-['Rosario']">Acts as a reference for orphan page detection.</li>
          <li className="text-xl md:text-2xl font-['Rosario']">Improves crawling efficiency.</li>
        </ul>
        <p className="text-lg font-semibold  font-['Rosario']">Without a sitemap, orphan page analysis is not possible.</p>
      </section>

      <section className="mt-4 p-4 bg-gray-100 rounded-2xl">
        <h2 className="text-2xl md:text-3xl font-bold font-['Libre_Baskerville']">Why Orphan Pages Are Bad for SEO</h2>
        <p className="text-xl md:text-2xl font-['Rosario']">Orphan pages can negatively impact your website’s SEO performance in several ways:</p>
        <ul className="list-disc pl-6 mt-2">
          <li className="text-xl md:text-2xl font-['Rosario']">Search engines may not crawl or index them.</li> 
          <li className="text-xl md:text-2xl font-['Rosario']">No internal link authority is passed.</li>
          <li className="text-xl md:text-2xl font-['Rosario']">Reduced visibility in search results.</li>
          <li className="text-xl md:text-2xl font-['Rosario']">Wasted content and ranking potential.</li>
        </ul>
        <p className="text-lg font-normal font-['Rosario']">Fixing orphan pages helps improve crawlability, indexing, and overall website health.</p>
      </section>

      <section className="mt-4 p-4 bg-gray-100 rounded-2xl">
        <h2 className="text-2xl md:text-3xl font-bold font-['Libre_Baskerville']">How to Fix Orphan Pages</h2>
        <p className="text-xl md:text-2xl font-['Rosario']">Once orphan pages are identified, you should:</p>
        <ul className="list-disc pl-6 mt-2">
          <li className="text-xl md:text-2xl font-['Rosario']">Add internal links from relevant pages.</li> 
          <li className="text-xl md:text-2xl font-['Rosario']">Include them in navigation or category pages.</li>
          <li className="text-xl md:text-2xl font-['Rosario']">Improve your internal linking structure.</li>
          <li className="text-xl md:text-2xl font-['Rosario']">Update sitemap after fixing links.</li>
        </ul>
        <p className="text-lg font-normal font-['Rosario']">These steps help search engines properly discover and rank your content.</p>
      </section>

      <section className="mt-4 p-4 bg-gray-100 rounded-2xl">
        <h2 className="text-2xl md:text-3xl font-bold font-['Libre_Baskerville']">Who Should Use This Tool</h2>
        <p className="text-xl md:text-2xl font-['Rosario']">This tool is ideal for:</p>
        <ul className="list-disc pl-6 mt-2">
          <li className="text-xl md:text-2xl font-['Rosario']">SEO professionals.</li> 
          <li className="text-xl md:text-2xl font-['Rosario']">Website owners.</li>
          <li className="text-xl md:text-2xl font-['Rosario']">Digital marketers.</li>
          <li className="text-xl md:text-2xl font-['Rosario']">Developers managing large websites.</li>
          <li className="text-xl md:text-2xl font-['Rosario']">Anyone looking to improve site structure and SEO health.</li>
        </ul>
      </section>    
    </main>
  )
}

export default Page;