'use client'
import { useState, useEffect } from 'react' 
import { useRouter } from 'next/navigation' 
import { Link as LinkIcon } from 'lucide-react' 
import axios from 'axios'
import jsPDF from 'jspdf';
import autoTable from 'jspdf-autotable';
import '@fortawesome/fontawesome-free/css/all.min.css';

const Page = () => {
  const router = useRouter()
  const [website, setWebsite] = useState("") 
  const [result, setResult] = useState(null) 
  const [loading, setLoading] = useState(false) 

  useEffect(() => {
    const token = localStorage.getItem("token")
    if (!token) {
      if (!window.hasShownAlert) {
        window.hasShownAlert = true;
        alert("Please login first to use this tool!")
        router.push('/signin') 
        setTimeout(() => { window.hasShownAlert = false; }, 3000);
      }
    }
  }, [router])

  // ✅ FIX 1: downloadBrokenPDF ko handleSubmit se BAHAR nikaal diya
const downloadBrokenPDF = async () => {
  if (!result) return;
  const doc = new jsPDF('p', 'mm', 'a4');
  const today = new Date().toLocaleDateString('en-GB');

  // 1. DATA CALCULATIONS
  const total = result.totalLinks || 0;
  const brokenCount = result.brokenLinks?.length || 0;
  const healthy = total - brokenCount;
  const healthScore = total > 0 ? ((healthy / total) * 100).toFixed(1) : 0;

  // --- 2. HEADER (Logo & Branding) ---
  try {
    const logoX = 15;
    const logoY = 10;
    const logoWidth = 25; 
    const logoHeight = 14;
    doc.addImage("/logo/pdf logo.png", "PNG", logoX, logoY, logoWidth, logoHeight);

    doc.setFont("helvetica", "bold");
    doc.setFontSize(22);
    doc.setTextColor(237, 109, 7);
    doc.text("LINKSENTINEL", 50, 23);
  } catch (e) {
    console.log("Logo missing");
  }

  doc.setFontSize(9);
  doc.setTextColor(150);
  doc.text("REPORT GENERATED BY LINKSENTINEL.COM", 195, 21, { align: "right" });
  doc.setDrawColor(220);
  doc.line(15, 33, 195, 33);

  // --- 3. TARGET WEBSITE BOX (Button Style) ---
  doc.setFont("helvetica", "bold");
  doc.setFontSize(18);
  doc.setTextColor(30, 41, 59);
  doc.text("Broken Link Analysis Report", 15, 45);

  const targetBoxY = 52;
  doc.setFillColor(248, 250, 252);
  doc.setDrawColor(220);
  doc.roundedRect(15, targetBoxY, 180, 14, 2, 2, "FD");

  doc.setFillColor(237, 109, 7);
  doc.roundedRect(18, targetBoxY + 3, 35, 8, 1, 1, "F"); 
  doc.setFontSize(8);
  doc.setTextColor(255);
  doc.text("TARGET WEBSITE", 35.5, targetBoxY + 8.5, { align: "center" });

  doc.setFontSize(9);
  doc.setTextColor(30, 41, 59);
  doc.setFont("helvetica", "normal");
  doc.text(website, 58, targetBoxY + 8.5);
  
  doc.setTextColor(120);
  doc.text(`Date: ${today}`, 190, targetBoxY + 8.5, { align: "right" });

  // --- 4. SUMMARY BAR (Full Width) ---
  const summaryY = 72;
  doc.setFillColor(245, 245, 245);
  doc.roundedRect(15, summaryY, 180, 15, 2, 2, "F");

  doc.setFontSize(11);
  doc.setTextColor(60);
  doc.setFont("helvetica", "bold");
  doc.text(`Total Links: ${total}`, 25, summaryY + 9);
  
  doc.setTextColor(239, 68, 68);
  doc.text(`Broken Links: ${brokenCount}`, 85, summaryY + 9);
  
  doc.setTextColor(60);
  doc.text(`Health Score: ${healthScore}%`, 145, summaryY + 9);

  // --- 5. DATA TABLE (Full Width) ---
  // Pie chart hata diya hai, ab table poori chaurai mein aayegi
  autoTable(doc, {
    startY: 95,
    margin: { left: 15, right: 15 },
    head: [['Sr.', 'Broken URL Path', 'Status Code']],
    body: (result.brokenLinks || []).map((link, i) => [
      i + 1, 
      link.url, 
      link.status
    ]),
    headStyles: { fillColor: [237, 109, 7], textColor: 255, fontStyle: 'bold' },
    styles: { fontSize: 8, cellPadding: 3, overflow: 'linebreak' },
    columnStyles: {
      0: { cellWidth: 15 },
      1: { cellWidth: 'auto' },
      2: { cellWidth: 30, halign: 'center' }
    },
    theme: 'grid'
  });

  // Footer
  const pageCount = doc.internal.getNumberOfPages();
  for (let i = 1; i <= pageCount; i++) {
    doc.setPage(i);
    doc.setFontSize(8);
    doc.setTextColor(150);
    doc.text(`Page ${i} of ${pageCount} - Broken Link Analysis by LinkSentinel`, 105, 285, { align: "center" });
  }

  doc.save(`BrokenLinks_Report_${today.replace(/\//g, '-')}.pdf`);
};

  // ✅ FIX 2: handleSubmit ko sahi se define kiya (Duplicate hataya)
  const handleSubmit = async (e) => {
    e.preventDefault();
    setResult(null);
    try {
      setLoading(true);
      const token = localStorage.getItem("token");
      const res = await axios.post(
        "http://localhost:5000/api/broken",
        { website },
        { headers: { Authorization: `Bearer ${token}` } }
      );
      setResult(res.data); 
    } catch (error) {
      console.error(error);
      alert("Scan failed. Please try again.");
    } finally {
      setLoading(false);
    }
  };
  return (
    <main className="m-8">
      <section className="mt-4 p-4 bg-gray-100 rounded-2xl">
      <h1 className="text-3xl md:text-4xl font-bold font-['Lora']">Broken Link Checker</h1>
    <h2 className="text-2xl md:text-3xl font-semibold font-['Lora']">Detect and Fix Broken Links That Harm Your SEO</h2>
    <div className="text-xl font-['DM Sans'] space-y-1.5">
       <p>Broken links are hyperlinks that lead to pages or resources that no longer exist or cannot be accessed. These links create a poor user experience and negatively affect your website’s SEO performance.</p>
      <p>The <span className="font-bold">Broken Link Checker Tool</span> scans your website and identifies links that return errors such as 404 (Page Not Found), server errors, or unreachable URLs.</p>
      </div>
   
      </section>

      
    
<form onSubmit={handleSubmit} className="mt-2 p-4 ">
  <label
    htmlFor="website-url"
    className="text-2xl font-['Lora'] text-black"
  >
    Enter your website URL
  </label>

  <div className="flex items-center gap-3 mt-2">
    {/* Input */}
    <div className="flex items-center border-2 gap-2.5 p-2.5 border-gray-500 rounded-md w-[340px]">
      <LinkIcon size={20} absoluteStrokeWidth />
      <input
        className="text-black outline-none flex-1"
        type="url"
        id="website-url"
        placeholder="https://example.com"
        value={website} 
       onChange={(e) => setWebsite(e.target.value)}
        required
      />
    </div>
    {/* Button */}
    <button
      type="submit"
      className="finline-flex items-center justify-center px-3 py-2 mr-3 text-xl font-['Lora'] font-medium text-center text-white rounded-lg bg-red-600 ring-2 ring-red-600 ring-offset-2 cursor-pointer transition-transform transform hover:scale-95"
    >
      <i className="fa-brands fa-searchengin fa-lg"></i>
      <span>Analysis</span>
    </button>
  </div>
  {/* note text  */}
  <p className="mt-2 text-red-600 text-sm">
    *Make sure your Website Url is valid.
  </p>
</form>


{loading && (
  <div className="mt-4 p-4 bg-blue-50 border-l-4 border-blue-500 text-blue-700 animate-pulse">
    <p className="font-bold">Crawling your website...</p>
    <p className="text-sm italic text-gray-600">This may take a minute depending on the number of links.</p>
  </div>
)}

{/*  RESULTS SECTION:  */}
{result && (
  <section className="mt-6 p-6 bg-white border-2 border-red-500 rounded-2xl shadow-lg">
    <div className="flex justify-between items-center mb-6 border-b pb-2">
      <h2 className="text-2xl font-bold text-red-600">Broken Link Report</h2>
      
      {/* 🔘 Download PDF Button */}
      <button 
        onClick={downloadBrokenPDF} // Ye wahi function hai jo maine pehle diya tha
        className="bg-[#ED6D07] hover:bg-orange-600 text-white px-4 py-2 rounded-lg font-bold flex items-center gap-2 transition-all active:scale-95 text-sm"
      >
        <i className="fa-solid fa-file-pdf"></i> Download PDF
      </button>
    </div>


    
    <div className="grid grid-cols-1 md:grid-cols-2 gap-4 mb-6">
      <div className="p-4 bg-gray-100 rounded-lg">
        <p className="text-gray-500">Total Unique Links Found</p>
        <p className="text-3xl font-bold">{result.totalLinks}</p>
      </div>
      <div className={`p-4 rounded-lg ${result.brokenLinks.length > 0 ? 'bg-red-50' : 'bg-green-50'}`}>
        <p className="text-gray-500">Broken Links Detected</p>
        <p className={`text-3xl font-bold ${result.brokenLinks.length > 0 ? 'text-red-600' : 'text-green-600'}`}>
          {result.brokenLinks.length}
        </p>
      </div>
    </div>

    {/* Broken Links table */}
    {result.brokenLinks.length > 0 ? (
      <div className="max-h-60 overflow-y-auto border rounded-lg">
        <table className="min-w-full bg-white">
          <thead className="sticky top-0 bg-gray-100">
            <tr>
              <th className="px-4 py-2 border text-left">Broken URL</th>
              <th className="px-4 py-2 border text-left">Status</th>
            </tr>
          </thead>
          <tbody>
            {result.brokenLinks.map((link, index) => (
              <tr key={index} className="hover:bg-gray-50">
                <td className="px-4 py-2 border text-blue-600 text-sm truncate max-w-xs">{link.url}</td>
                <td className="px-4 py-2 border">
                  <span className="px-2 py-1 bg-red-100 text-red-700 rounded text-xs font-bold">{link.status}</span>
                </td>
              </tr>
            ))}
          </tbody>
        </table>
      </div>
    ) : (
      <p className="text-green-600 font-bold italic">No broken links found!</p>
    )}
  </section>
)}

<section className="mt-4 p-4 bg-gray-100 rounded-2xl">
        <h2 className="text-2xl md:text-3xl font-bold font-['Lora']">How the Broken Link Checker Works.</h2>
        <p className="text-xl md:text-2xl font-['Rosario']">This tool uses automated crawling to detect broken or non-working links across your website.</p>
        <p className="text-xl font-semibold md:text-2xl font-['Rosario']">Step-by-Step Process:</p>
        <ol className="list-decimal pl-6 mt-2">
          <li className="text-xl md:text-2xl font-['Rosario']">The tool crawls all accessible pages of your website.</li> 
          <li className="text-xl md:text-2xl font-['Rosario']">It extracts all internal and external links.</li>
          <li className="text-xl md:text-2xl font-['Rosario']">Each link is checked for response status.</li>
          <li className="text-xl md:text-2xl font-['Rosario']">Links returning error responses are marked as <span className='font-bold'>Broken Links</span>.</li>
          <li className="text-xl md:text-2xl font-['Rosario']">A detailed report is generated for review.</li>
        </ol>
      </section>

       <section className="mt-4 bg-gray-100 p-4 rounded-2xl">
      <h2 className="text-2xl md:text-3xl font-bold font-['Lora']">Types of Broken Links Detected</h2>
      <p className="mt-2 text-xl md:text-2xl font-['Rosario']">The tool identifies multiple types of broken links including:</p>
        <ul className="mt-2 space-y-2 pl-2">
          <li>
            <h4 className="text-xl font-semibold md:text-2xl font-['Lora']">404 Error (Page Not Found)
            </h4>
            <p className="text-xl md:text-2xl font-['Rosario']">The requested page does not exist on the server.
            </p>
          </li>
          <li>
            <h4 className="text-xl font-semibold md:text-2xl font-['Lora']">Server Errors (500 Errors)
            </h4>
            <p className="text-xl md:text-2xl font-['Rosario']">Indicates server issues that prevent page loading.
            </p>
          </li>
          <li>
            <h4 className="text-xl font-semibold md:text-2xl font-['Lora']">Redirect Errors
            </h4>
            <p className="text-xl md:text-2xl font-['Rosario']">Improper or broken redirections leading to inaccessible pages.
            </p>
          </li>
          <li>
            <h4 className="text-xl font-semibold md:text-2xl font-['Lora']">Timeout / Unreachable Links
            </h4>
            <p className="text-xl md:text-2xl font-['Rosario']">Links that fail to respond or take too long to load.
            </p>
          </li>
        </ul>
    </section>

      <section className="mt-4 p-4 bg-gray-100 rounded-2xl">
        <h2 className="text-2xl md:text-3xl font-bold font-['Lora']">Broken Link Analysis Results</h2>
        <p className="text-xl md:text-2xl font-['Rosario']">Once scanning is complete, a detailed report will be displayed below.</p>
        <p className="text-xl font-semibold md:text-2xl font-['Rosario']">The Report Includes:</p>
        <ul className="list-disc pl-6 mt-2">
          <li className="text-xl md:text-2xl font-['Rosario']">Total pages crawled.</li> 
          <li className="text-xl md:text-2xl font-['Rosario']">Total links found.</li>
          <li className="text-xl md:text-2xl font-['Rosario']">Total broken links detected.</li>
          <li className="text-xl md:text-2xl font-['Rosario']">Status code of each broken link.</li>
          <li className="text-xl md:text-2xl font-['Rosario']">Source page where broken link exists.</li>
          <li className="text-xl md:text-2xl font-['Rosario']">Broken link URL.</li>
        </ul>
        <p className="text-xl md:text-2xl font-['Rosario']">This information helps users quickly identify and fix issues.</p>
      </section>

      <section className="mt-4 p-4 bg-gray-100 rounded-2xl">
        <h2 className="text-2xl md:text-3xl font-bold font-['Lora']">Why Broken Links Are Bad for SEO</h2>
        <p className="text-xl md:text-2xl font-['Rosario']">Broken links can significantly harm your website’s performance:</p>
        <ul className="list-disc pl-6 mt-2">
          <li className="text-xl md:text-2xl font-['Rosario']">Poor user experience.</li> 
          <li className="text-xl md:text-2xl font-['Rosario']">Increased bounce rate.</li>
          <li className="text-xl md:text-2xl font-['Rosario']">Negative search engine ranking signals.</li>
          <li className="text-xl md:text-2xl font-['Rosario']">Reduced website credibility.</li>
          <li className="text-xl md:text-2xl font-['Rosario']">Crawl budget wastage.</li>
        </ul>
        <p className="text-xl md:text-2xl font-['Rosario']">Fixing broken links improves website usability and SEO performance.</p>
      </section>

      <section className="mt-4 p-4 bg-gray-100 rounded-2xl">
        <h2 className="text-2xl md:text-3xl font-bold font-['Lora']">How to Fix Broken Links</h2>
        <p className="text-xl md:text-2xl font-['Rosario']">After identifying broken links, you can fix them by:</p>
        <ul className="list-disc pl-6 mt-2">
          <li className="text-xl md:text-2xl font-['Rosario']">Updating incorrect URLs.</li> 
          <li className="text-xl md:text-2xl font-['Rosario']">Replacing broken links with working alternatives.</li>
          <li className="text-xl md:text-2xl font-['Rosario']">Removing outdated or deleted page links.</li>
          <li className="text-xl md:text-2xl font-['Rosario']">Setting up proper redirects (301 redirects).</li>
          <li className="text-xl md:text-2xl font-['Rosario']">Restoring deleted pages if necessary.</li>
        </ul>
      </section>

      <section className="mt-4 p-4 bg-gray-100 rounded-2xl">
        <h2 className="text-2xl md:text-3xl font-bold font-['Lora']">Internal vs External Broken Links</h2>
        <h3 className="text-xl font-semibold md:text-2xl font-['Rosario']">Internal Broken Links</h3>
        <p className="text-xl md:text-2xl font-['Rosario']">Links that point to pages within your website but lead to errors.</p>
        <p className="mt-2.5 text-xl md:text-2xl font-['Rosario']">These affect:</p>
        <ul className="list-disc pl-6 mt-2">
          <li className="text-xl md:text-2xl font-['Rosario']">Website navigation.</li> 
          <li className="text-xl md:text-2xl font-['Rosario']">Internal linking structure.</li>
          <li className="text-xl md:text-2xl font-['Rosario']">SEO ranking signals.</li>
        </ul>
        <hr className="border-t-gray-300 border-t-2 my-4"></hr>
        <h3 className="text-xl font-semibold md:text-2xl font-['Rosario']">External Broken Links</h3>
        <p className="text-xl md:text-2xl font-['Rosario']">Links pointing to other websites that are no longer available.</p>
        <p className="mt-2.5 text-xl md:text-2xl font-['Rosario']">These affect:</p>
        <ul className="list-disc pl-6 mt-2">
          <li className="text-xl md:text-2xl font-['Rosario']">Content credibility.</li> 
          <li className="text-xl md:text-2xl font-['Rosario']">User trust.</li>
          <li className="text-xl md:text-2xl font-['Rosario']">Outbound link quality.</li>
        </ul>
      </section> 

       <section className="mt-4 p-4 bg-gray-100 rounded-2xl">
        <h2 className="text-2xl md:text-3xl font-bold font-['Lora']">Who Should Use This Tool</h2>
        <p className="text-xl md:text-2xl font-['Rosario']">This tool is ideal for:</p>
        <ul className="list-disc pl-6 mt-2">
          <li className="text-xl md:text-2xl font-['Rosario']">SEO professionals.</li> 
          <li className="text-xl md:text-2xl font-['Rosario']">Website owners.</li>
          <li className="text-xl md:text-2xl font-['Rosario']">Developers.</li>
          <li className="text-xl md:text-2xl font-['Rosario']">Content managers.</li>
          <li className="text-xl md:text-2xl font-['Rosario']">Digital marketing teams.</li>
        </ul>
        <p className="text-xl md:text-2xl font-['Rosario']">Anyone managing website content can benefit from broken link detection.</p>
      </section>   
    </main>
  )
}

export default Page;